# Generated by Django 5.1.2 on 2024-10-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prato', models.CharField(max_length=150)),
                ('preco', models.IntegerField()),
                ('porcao', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Carros',
        ),
    ]
